package Employee;

import static Employee.NewClass.viso;
import static Employee.loan.isNumeric;
import static Employee.loan.loan;
import graphs.graph;
import graphs.graphatidejlin;
import java.awt.EventQueue;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Aukse Levonaite 5 group
 */
public class Frame extends javax.swing.JFrame {

    public static double nuo1;
    public static double iki1;
    public static double palukana;
    public static double kiek;
    public static double sumt;
    public Frame() {
        initComponents();
       
    }
    public Frame(double kiek, double sumt){
        this.kiek = kiek;
        this.sumt = sumt;
        setKiek(kiek);
        setSumt(sumt);
    }
    
    
    public double getKiek() {
        return kiek;
    }

    public void setKiek(double kiek) {
        this.kiek = kiek;
    }

    public static double getSumt() {
        return sumt;
    }

    public static void setSumt(double sumt) {
        Frame.sumt = sumt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jnuo1 = new javax.swing.JTextField();
        jiki1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jpaluk = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jgraph = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("From");

        jLabel2.setText("To");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setText("Input period of delay and interest rate:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Interest rate");

        jButton1.setText("Recalculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jgraph.setText("Graph");
        jgraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgraphActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jnuo1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jiki1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpaluk, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jgraph)
                                .addGap(34, 34, 34)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jnuo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jiki1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpaluk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jgraph)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String atid = String.format(jnuo1.getText());
        if(isNumeric(atid) == false){
             JOptionPane.showMessageDialog(null,"You must enter period from", "Loan system", JOptionPane.INFORMATION_MESSAGE);   
        }
        else if(jnuo1.getText().equals("") ){
            JOptionPane.showMessageDialog(null,"You must enter period from", "Loan system", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(Double.parseDouble(jnuo1.getText()) < 0){
            JOptionPane.showMessageDialog(null,"You must enter positive month of period from", "Loan system", JOptionPane.INFORMATION_MESSAGE);
        }
            else {
            nuo1 = Double.parseDouble(jnuo1.getText());  
        } 
           String atidiki = String.format(jiki1.getText());
           if(isNumeric(atidiki) == false){
             JOptionPane.showMessageDialog(null,"You must enter period to", "Loan system", JOptionPane.INFORMATION_MESSAGE);   
        }
           else if(jiki1.getText().equals("") ){
            JOptionPane.showMessageDialog(null,"You must enter period to", "Loan system", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(Double.parseDouble(jiki1.getText()) < 0){
            JOptionPane.showMessageDialog(null,"You must enter positive month of period to", "Loan system", JOptionPane.INFORMATION_MESSAGE);
        }
            else {
            iki1 = Double.parseDouble(jiki1.getText()); 
        } 
          String atidpask = String.format(jpaluk.getText());
          if(isNumeric(atidpask) == false){
             JOptionPane.showMessageDialog(null,"You must enter interest rate", "Loan system", JOptionPane.INFORMATION_MESSAGE);   
        }
          else if(jpaluk.getText().equals("") ){
            JOptionPane.showMessageDialog(null,"You must enter interest rate", "Loan system", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(Double.parseDouble(jpaluk.getText()) < 0){
            JOptionPane.showMessageDialog(null,"You must enter positive interest rate", "Loan system", JOptionPane.INFORMATION_MESSAGE);
        }
            else {
            palukana = Double.parseDouble(jpaluk.getText()); 
        } 
        NewClass clas1 = new NewClass();
         loan g = new loan();
         atidejimaslinij atl = new atidejimaslinij();
        if(getKiek() == 1){
            try {
                clas1.atidejimas(nuo1, iki1);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        else if(getSumt() ==1){
            try {
                atl.atidejimas2(nuo1, iki1);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed
    private void jgraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgraphActionPerformed
         loan g = new loan();
        if (getKiek() ==1) {
            EventQueue.invokeLater(() -> {  
            graph ex = null;
             try {
                 ex = new graph();
             } catch (IOException ex1) {
                 Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex1);
             }
            ex.setVisible(true);
        });
        }
         if (getSumt()==1) {
            EventQueue.invokeLater(() -> {  
            graphatidejlin ex = null;
             try {
                 ex = new graphatidejlin();
             } catch (IOException ex1) {
                 Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex1);
             }
            ex.setVisible(true);
        });
        }
        
        
        
    }//GEN-LAST:event_jgraphActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jgraph;
    private javax.swing.JTextField jiki1;
    private javax.swing.JTextField jnuo1;
    private javax.swing.JTextField jpaluk;
    // End of variables declaration//GEN-END:variables
}
